services:
  harmony:
    volumes:
      - .:/app
      - ./database:/database
      - ./logs:/logs
      - ./test_music:/music
      - ./downloads:/downloads

    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8080
      --reload